export const zhChat: Record<string, string> = {
  "Hi — I'm your AI teammate 👋\n\nI run tasks on a computer of my own and work across your connected tools — Slack, Google Workspace, GitHub, Linear, and the open web — and I remember what we work on together.\n\nWant to get set up? Tell me your name and what you're working on, and I'll take it from there — or just ask me anything to dive straight in.":
    "你好 — 我是你的 AI 队友 👋\n\n我在自己的电脑上执行任务，跨你已连接的工具工作 — Slack、Google Workspace、GitHub、Linear 以及开放的互联网 — 并且会记住我们一起做的事情。\n\n想开始设置吗？告诉我你的名字和正在做的事情，剩下的交给我 — 或者直接问我任何问题，马上开始。",
  "Ask anything": "有什么问题尽管问",
  "Loading runtime…": "正在加载运行时…",
  "Approve or deny to continue": "批准或拒绝以继续",
  "Steer the running task…": "干预正在运行的任务…",
  "Steer the running task": "干预正在运行的任务",
  "Steer the running task (attachments stay for your next message)":
    "干预正在运行的任务（附件会留给你的下一条消息）",
  "↪ steered the running task": "↪ 干预了正在运行的任务",
  "Could not steer the running task.": "无法干预正在运行的任务。",
  "Preparing files...": "正在准备文件…",
  Retry: "重试",
  "Loading runtime settings…": "正在加载运行时设置…",
  "Could not load runtime settings.": "无法加载运行时设置。",
  "Could not update the scope default.": "无法更新该上下文的默认设置。",
  "The org now recommends {harness} · {model}.": "组织现在推荐 {harness} · {model}。",
  Upgrade: "升级",
  "Keep mine": "保留我的选择",
  "Inherit future defaults": "沿用以后的默认",
  "View pasted text": "查看粘贴的文本",
  "Pasted text": "粘贴的文本",
  Remove: "移除",
  "Insert into message": "插入到消息中",
  Done: "完成",
  Close: "关闭",
  "Attach files": "附加文件",
  Effort: "强度",
  Auto: "自动",
  Low: "低",
  Medium: "中",
  High: "高",
  XHigh: "超高",
  Max: "最高",
  Fast: "快速",
  "Fast mode": "快速模式",
  "Fast mode active": "快速模式已开启",
  "Fast mode is only available on Opus models": "快速模式仅适用于 Opus 模型",
  "Make default": "设为默认",
  Default: "默认",
  "Use this harness and model as the default for this scope": "将此 harness 和模型设为此上下文的默认",
  "Use org default": "使用组织默认",
  "Org default": "组织默认",
  Model: "模型",
  Harness: "Harness",
  "Session settings — {summary}": "会话设置 — {summary}",
  Send: "发送",
  Stop: "停止",
  "Command approval": "命令批准",
  Deny: "拒绝",
  "Allow once": "允许一次",
  "Allow for session": "本会话内允许",
  "Allow always": "始终允许",
  Skills: "技能",
  "Loading skills…": "正在加载技能…",
  Personal: "个人",
  Team: "团队",
  Organization: "组织",
  Org: "组织",
  "Could not deliver the message — the running task never settled. It is back in the composer.":
    "无法送达消息 — 正在运行的任务始终未就绪。消息已放回输入框。",
  "Could not deliver the message — the running task ended mid-send. It is back in the composer.":
    "无法送达消息 — 正在运行的任务在发送中途结束了。消息已放回输入框。",
  "Could not send message.": "无法发送消息。",
  "Still preparing the previous drop — try again in a moment.": "上一个拖入的内容还在准备中 — 请稍候再试。",
  "That drop included a folder this browser can't read — zip it and drop the archive instead.":
    "拖入的内容包含此浏览器无法读取的文件夹 — 请先压缩成 zip 再拖入压缩包。",
  "Could not attach that file.": "无法附加该文件。",
  "Drop files or folders to attach": "拖入文件或文件夹以附加",
  "Could not start the conversation.": "无法开始对话。",
  "Could not send the approval.": "无法发送批准。",
  "Could not reconnect to the running task.": "无法重新连接到正在运行的任务。",
  "This conversation lives in Slack. Replies happen there.": "此对话位于 Slack，回复需在 Slack 中进行。",
  "Open in Slack": "在 Slack 中打开",
  "This conversation is read-only here.": "此对话在此处为只读。",
  "Read-only": "只读",
  "Loading earlier messages…": "正在加载更早的消息…",
  "Show earlier messages": "显示更早的消息",
  "No readable messages in this conversation.": "此对话中没有可显示的消息。",
  "Expand this pane": "展开此面板",
  Now: "正在",
  "Needs your approval": "需要你的批准",
  "Thinking…": "正在思考…",
  Thinking: "思考中",
  "This chat runs in the {label} context — the agent works with that context's files and memory, separate from your personal context.":
    "此对话运行在 {label} 上下文中 — 代理使用该上下文的文件和记忆，与你的个人上下文相互独立。",
  context: "上下文",
  "View session log (admin)": "查看会话日志（管理员）",
  "Refresh conversations": "刷新会话",
  Stopped: "已停止",
  Copy: "复制",
  "Copy message": "复制消息",
  "Fork conversation from here": "从此处分叉对话",
  "Could not fork the conversation.": "无法分叉对话。",
  "your account": "你的账号",
  "Connected {name}": "已连接 {name}",
  "Authorized — its tools work here now": "已授权 — 其工具现在可在此使用",
  "Connect {name}": "连接 {name}",
  "Authorize access in a new tab": "在新标签页中授权访问",
  "Failed to load background activity.": "加载后台活动失败。",
  expiring: "即将到期",
  "{mins}m left": "剩余 {mins} 分钟",
  "{hours}h {mins}m left": "剩余 {hours} 小时 {mins} 分",
  "Hide background activity": "隐藏后台活动",
  "Work continuing on the agent's computer — click to inspect": "代理的电脑上仍有工作在继续 — 点击查看",
  "Background activity": "后台活动",
  "Loading…": "正在加载…",
  "Nothing running here anymore.": "这里已经没有在运行的任务了。",
  exited: "已退出",
  "Hide output": "隐藏输出",
  "Show live output": "显示实时输出",
  "started {when}": "启动于 {when}",
  "(no output yet)": "（暂无输出）",
  "Loading output…": "正在加载输出…",
  "output matching /{pattern}/": "匹配 /{pattern}/ 的输出",
  "any new output": "任何新输出",
  "Watch — wakes on {what}": "监视 — 出现{what}时唤醒",
  "armed {when}": "设置于 {when}",
  "last fired {when}": "上次触发 {when}",
  "Show less": "收起",
  "Show more": "展开",
  "{verb} interrupted — resuming…": "{verb}中断 — 正在恢复…",
  "Interrupted — resuming…": "已中断 — 正在恢复…",
  "{label} for {secs}s": "{label} {secs} 秒",
  " (used 1 tool)": "（已使用 1 个工具）",
  " (used {n} tools)": "（已使用 {n} 个工具）",
  "Working for {secs}s": "正在工作 {secs} 秒",
  "Worked for {secs}s": "工作了 {secs} 秒",
  "1 tool call": "1 次工具调用",
  "{tools} tool calls": "{tools} 次工具调用",
  "Failed after {secs}s": "{secs} 秒后失败",
  "Approval needed": "需要批准",
  Why: "原因",
  "Triggered by": "触发来源",
  "Show full command": "显示完整命令",
  "Show full output": "显示完整输出",
  "Running command": "正在运行命令",
  "Ran command": "已运行命令",
  "Tried command": "尝试运行命令",
  "Reading file": "正在读取文件",
  "Read file": "已读取文件",
  "Tried reading file": "尝试读取文件",
  "Writing file": "正在写入文件",
  "Wrote file": "已写入文件",
  "Tried writing file": "尝试写入文件",
  Publishing: "正在发布",
  Published: "已发布",
  "Tried publishing": "尝试发布",
  "Searching memory": "正在搜索记忆",
  "Searched memory": "已搜索记忆",
  "Tried searching memory": "尝试搜索记忆",
  "Using memory": "正在使用记忆",
  "Used memory": "已使用记忆",
  "Tried using memory": "尝试使用记忆",
  "Searching history": "正在搜索历史",
  "Searched history": "已搜索历史",
  "Tried searching history": "尝试搜索历史",
  "Managing process": "正在管理进程",
  "Managed process": "已管理进程",
  "Tried managing process": "尝试管理进程",
  Working: "正在工作",
  "Finished step": "已完成步骤",
  "Tried step": "尝试了步骤",
  "{label} — interrupted": "{label} — 已中断",
  "{attempts} attempts": "{attempts} 次尝试",
  "1 result": "1 条结果",
  "{count} results": "{count} 条结果",
  "{added} saved": "已保存 {added} 条",
  "exit {code}": "退出码 {code}",
  " · timed out": " · 已超时",
  "Couldn't load the full output.": "无法加载完整输出。",
};
