export const zhDeploys: Record<string, string> = {
  Yours: "我的",
  Shared: "共享",
  Archived: "已归档",
  Running: "运行中",
  Stopped: "已停止",
  Deploying: "部署中",
  Unknown: "未知",
  Apps: "应用",
  "App view": "应用视图",
  "App actions": "应用操作",
  "More actions for {title}": "{title}的更多操作",
  Open: "打开",
  "Open app": "打开应用",
  "Copy app URL": "复制应用链接",
  "Copy URL": "复制链接",
  "Copy Git remote": "复制 Git 远程地址",
  Restore: "恢复",
  "Restore deployment": "恢复部署",
  "Edit display name": "编辑显示名称",
  "Change URL slug": "修改 URL 别名",
  Archive: "归档",
  "Archive deployment": "归档部署",
  "You own this app or have permission to manage it.": "你拥有此应用，或拥有管理它的权限。",
  "This app is shared with a context you can access. You can open and clone it, but not change it.":
    "此应用共享自你可访问的上下文。你可以打开和克隆它，但不能修改它。",
  "Can manage": "可管理",
  "Can view": "可查看",
  "Version unknown": "版本未知",
  "v{applied} live · v{current} pending": "v{applied} 在线 · v{current} 待生效",
  "Deployed {at}": "部署于{at}",
  "Deployment time unavailable": "部署时间不可用",
  "Your personal context": "你的个人上下文",
  "{name} · Personal": "{name} · 个人",
  Organization: "组织",
  "Shared context · created by {name}": "共享上下文 · 由 {name} 创建",
  "Shared context": "共享上下文",
  "Loading apps…": "正在加载应用…",
  "No apps match your search.": "没有匹配搜索的应用。",
  "No apps in this context.": "此上下文中没有应用。",
  "No apps shared with you.": "没有共享给你的应用。",
  "Nothing archived.": "没有已归档的应用。",
  "No apps of your own yet.": "你还没有自己的应用。",
  "Deploy with Agent": "让 Agent 部署",
  Sort: "排序",
  "Sort apps": "排序应用",
  Newest: "最新",
  Name: "名称",
  Status: "状态",
  "Search apps": "搜索应用",
  Refresh: "刷新",
  "Failed to load apps.": "加载应用失败。",
  "Could not load app details.": "无法加载应用详情。",
  "Loading authoritative app details…": "正在从服务端加载应用详情…",
  "Edit live": "在线编辑",
  "Could not open live editing.": "无法打开在线编辑。",
  Overview: "概览",
  "Live version": "在线版本",
  "Latest version": "最新版本",
  "Last deployed": "最近部署",
  "Last opened": "最近打开",
  "No recorded access": "无访问记录",
  Access: "访问权限",
  "Ownership and access": "归属与访问",
  "Created in": "创建于",
  Owner: "所有者",
  "Created by": "创建者",
  "Git remote": "Git 远程仓库",
  "Clone or push a new version with this short-lived authenticated URL.":
    "使用这个短期有效的认证地址克隆或推送新版本。",
  "Clone source with this short-lived read-only authenticated URL.":
    "使用这个短期有效的只读认证地址克隆源码。",
  Settings: "设置",
  "Display name": "显示名称",
  "The human-friendly name shown here. This does not change the app URL.":
    "此处展示的易读名称，不会改变应用 URL。",
  "Using URL slug": "正使用 URL 别名",
  Edit: "编辑",
  "URL slug": "URL 别名",
  "Changes the app URL. Existing links do not redirect.": "会改变应用 URL，已有链接不会重定向。",
  Change: "修改",
  "A URL slug is required.": "URL 别名不能为空。",
  "{title} settings saved.": "{title}的设置已保存。",
  "Could not save app settings.": "无法保存应用设置。",
  Save: "保存",
  Cancel: "取消",
  "Version history": "版本历史",
  Live: "在线",
  Latest: "最新",
  "No version history available.": "暂无版本历史。",
  "Archive {title}?": "归档 {title}？",
  "This takes the app offline immediately, so its current URL will stop working. Its source and version history are kept, and you can restore it later.":
    "应用会立即下线，当前 URL 将停止工作。源码和版本历史会保留，之后可以随时恢复。",
  "Archive and take offline": "归档并下线",
  "Archiving deployment…": "正在归档部署…",
  "{title} is offline and archived.": "{title}已下线并归档。",
  "Could not archive deployment.": "无法归档部署。",
  "Restoring deployment…": "正在恢复部署…",
  "{title} is restored and running.": "{title}已恢复并正在运行。",
  "Could not restore deployment.": "无法恢复部署。",
  Undo: "撤销",
  Dismiss: "关闭",
  "Dismiss notification": "关闭通知",
  "Deploy an app for me.": "帮我部署一个应用。",
  "Unknown owner": "未知所有者",
};
