export const zhResources: Record<string, string> = {
  "{count}w": "{count} 周",
  "{count}d": "{count} 天",
  "{count}h": "{count} 小时",
  "{count}m": "{count} 分钟",
  "{count}s": "{count} 秒",
  "cron {expr}": "cron 表达式 {expr}",
  "every {interval}": "每 {interval}",
  "one-time": "一次性",
  "{summary} (default timezone)": "{summary}（默认时区）",
  "first run": "首次运行",
  run: "运行",
  "{summary} - {runLabel} {time}": "{summary} - {runLabel} {time}",
  "due {time}": "已到期 {time}",
  "next {time}": "下次 {time}",
  "last {time}": "上次 {time}",
  "first {time}": "首次 {time}",
  "never fired": "从未运行",
  "Next run: {time}": "下次运行：{time}",
  "Last fired: {time}": "上次运行：{time}",
  "First run: {time}": "首次运行：{time}",
  "Never fired": "从未运行",
  "tomorrow {time}": "明天 {time}",

  Yours: "你的",
  Shared: "共享",
  Archived: "已归档",
  "Failed to load crons.": "加载定时任务失败。",
  "(untitled cron)": "（未命名定时任务）",
  "org-wide": "全组织",
  group: "群组",
  Enabled: "已启用",
  Disabled: "已停用",
  "That cron wasn't found, or you don't have access to it.": "未找到该定时任务，或你没有访问权限。",
  "No active crons.": "没有运行中的定时任务。",
  "None of your own crons yet.": "你还没有自己的定时任务。",
  "No crons shared with you.": "没有与你共享的定时任务。",
  "Nothing archived.": "暂无归档内容。",
  "No crons yet.": "还没有定时任务。",
  "Loading crons…": "正在加载定时任务…",
  "No crons in this context.": "此上下文中没有定时任务。",
  "New cron": "新建定时任务",
  "Search crons": "搜索定时任务",
  "Cron view": "定时任务视图",
  "Hide disabled": "隐藏已停用",
  "Show disabled": "显示已停用",
  Enable: "启用",
  "Enable cron": "启用定时任务",
  Unarchive: "取消归档",
  "Unarchive cron": "取消归档定时任务",
  Disable: "停用",
  "Disable cron": "停用定时任务",
  Edit: "编辑",
  "Edit cron": "编辑定时任务",
  Archive: "归档",
  "Archive cron": "归档定时任务",
  "Cron actions": "定时任务操作",
  "Run now": "立即运行",
  Context: "上下文",
  Title: "标题",
  Message: "消息",
  Task: "任务",
  Schedule: "调度",
  Owner: "所有者",
  Scope: "范围",
  Status: "状态",
  Destination: "目标",
  "Next run": "下次运行",
  "Last fired": "上次运行",
  Never: "从未",
  "Shared from {scope} — you can view it, but not change it.": "共享自 {scope}——你可以查看，但不能修改。",
  "Recent runs": "最近运行",
  Refresh: "刷新",
  "Loading…": "正在加载…",
  "No runs yet.": "还没有运行记录。",
  completed: "已完成",
  Worklog: "工作日志",
  "Couldn't load run history.": "无法加载运行历史。",
  "Run started. Refresh recent runs after it completes.": "已开始运行。运行完成后请刷新最近运行。",
  "run failed": "运行失败",
  "edit failed": "编辑失败",
  "archive failed": "归档失败",
  "unarchive failed": "取消归档失败",
  "enable failed": "启用失败",
  "disable failed": "停用失败",
  "delete failed": "删除失败",
  "Delete {title}?": "删除 {title}？",
  "This permanently removes the schedule and its retained run history. Archive it instead if you may need it later.":
    "这将永久删除该调度及其保留的运行历史。如果以后可能还需要，请改为归档。",
  Cancel: "取消",
  "Delete permanently": "永久删除",
  Delete: "删除",
  "To change {what}, use the agent so it can validate the resulting behavior and permissions.":
    "要修改{what}，请通过代理操作，以便它验证修改后的行为和权限。",
  "the schedule, timezone, destination, or run mode": "调度、时区、目标或运行方式",
  "the message, schedule, timezone, destination, or run mode": "消息、调度、时区、目标或运行方式",
  "Edit behavior with agent": "让代理修改行为",
  Save: "保存",
  "Title and task are required.": "标题和任务为必填项。",
  "Title is required.": "标题为必填项。",
  "Cron updated.": "定时任务已更新。",
  "Describe what you want scheduled — what to do, how often, and where the result should go. The agent sets it up and confirms in chat; it will ask if anything is unclear. It should give the cron a short, distinctive title naming what it is for, like":
    "描述你想定时的内容——做什么、多久一次、结果发到哪里。代理会设置好并在对话中确认；有不清楚的地方它会询问。它应该给定时任务起一个简短、有辨识度的标题来说明用途，比如",
  or: "或",
  ".": "。",
  "Every weekday at 9am, summarize my unread email and DM me the highlights.":
    "每个工作日上午 9 点，总结我的未读邮件，并把要点私信发给我。",
  "Ask the agent to set it up": "让代理来设置",
  "Describe the cron you want.": "请描述你想要的定时任务。",

  "Drop files here or choose files": "将文件拖到此处，或点击选择文件",
  "Drop files": "拖放文件",
  "Uploading…": "正在上传…",
  "Loading files…": "正在加载文件…",
  "Files created, uploaded, or shared with you": "你创建、上传或与你共享的文件",
  Upload: "上传",
  "Search files": "搜索文件",
  "Search file names and types…": "搜索文件名和类型…",
  Ownership: "归属",
  "All files": "全部文件",
  Type: "类型",
  "All types": "全部类型",
  Images: "图片",
  Documents: "文档",
  Other: "其他",
  Sort: "排序",
  Newest: "最新",
  Oldest: "最早",
  Name: "名称",
  "No files match these filters.": "没有符合这些筛选条件的文件。",
  "No files yet. Upload one here or ask the agent to create one.":
    "还没有文件。在此上传一个，或让代理创建一个。",
  "Load more": "加载更多",
  Created: "已创建",
  Uploaded: "已上传",
  Open: "打开",
  Unavailable: "不可用",
  "Upload failed ({status})": "上传失败（{status}）",
  "Uploading {count} file…": "正在上传 {count} 个文件…",
  "Uploading {count} files…": "正在上传 {count} 个文件…",
  "Uploaded {count} file.": "已上传 {count} 个文件。",
  "Uploaded {count} files.": "已上传 {count} 个文件。",
  "Uploaded {done} of {total}.": "已上传 {done}/{total} 个。",
  "Upload failed.": "上传失败。",
  "Failed to load more files.": "加载更多文件失败。",
  "Failed to load all matching files.": "加载所有匹配文件失败。",
  "Failed to load files.": "加载文件失败。",

  '"{name}" has too many files (over {max}) — zip it yourself or drop a subfolder.':
    '"{name}" 里的文件太多（超过 {max} 个）——请自行压缩成 zip，或拖入其中的子文件夹。',
  '"{name}" is too big (over {mb} MB) — zip it yourself or drop a subfolder.':
    '"{name}" 太大（超过 {mb} MB）——请自行压缩成 zip，或拖入其中的子文件夹。',
  '"{name}" has no files in it.': '"{name}" 里面没有文件。',

  "Facts the agent carries into your conversations.": "代理会在你的对话中携带的事实。",
  "Facts view": "事实视图",
  "Edit notebook": "编辑笔记本",
  History: "历史",
  "Refresh memory": "刷新记忆",
  "Edit the notebook directly. Switch to Facts view to search or remove individual facts. Saves are protected if the agent remembers something new while this page is open.":
    "直接编辑笔记本。切换到事实视图可搜索或删除单条事实。如果在此页面打开期间代理记住了新内容，保存会受到冲突保护。",
  "Search memory": "搜索记忆",
  "Search remembered facts": "搜索已记住的事实",
  "Captured {date}": "记录于 {date}",
  "Forget this fact": "忘记这条事实",
  "No remembered facts match this search.": "没有符合搜索的已记住事实。",
  "The agent hasn’t noted any facts yet.": "代理还没有记录任何事实。",
  "Saving…": "正在保存…",
  "Save changes": "保存更改",
  "Unsaved changes": "有未保存的更改",
  "Revision history": "修订历史",
  Current: "当前",
  "Revision {rev}": "修订 {rev}",
  "automatic capture": "自动捕获",
  Restore: "恢复",
  "Revision history is unavailable for this memory store.": "此记忆存储没有可用的修订历史。",
  "Check impact": "检查影响",
  "Discard unsaved memory changes?": "放弃未保存的记忆更改？",
  "Refreshing will replace this draft with the latest memory. Copy anything you want to keep before continuing.":
    "刷新会用最新记忆替换当前草稿。继续之前，请复制任何想保留的内容。",
  "Discard and refresh": "放弃并刷新",
  "Failed to load memory.": "加载记忆失败。",
  "Saved ✓": "已保存 ✓",
  "Saved ✓ History could not refresh.": "已保存 ✓ 历史记录刷新失败。",
  "Memory changed in another conversation. Your draft is still here; copy it if needed, then refresh to merge with the latest version.":
    "记忆已在另一个对话中被修改。你的草稿仍在这里；如有需要请复制，然后刷新以与最新版本合并。",
  "Failed to save memory.": "保存记忆失败。",
  "Failed to load memory history.": "加载记忆历史失败。",
  "Restore memory from {date}?": "恢复 {date} 的记忆？",
  "The selected notebook will become current. The version you have now remains available in history.":
    "所选笔记本将成为当前版本。你现在的版本仍保留在历史中。",
  "Restore revision": "恢复此修订",
  "Revision restored ✓": "修订已恢复 ✓",
  "Revision restored ✓ History could not refresh.": "修订已恢复 ✓ 历史记录刷新失败。",
  "Could not restore that revision.": "无法恢复该修订。",

  "Gmail, Calendar, Drive, Sheets": "Gmail, Calendar, Drive, Sheets",
  "Channels & messages": "频道和消息",
  "Pages & databases": "页面和数据库",
  "Issues & projects": "议题和项目",
  "Repos, issues & PRs": "仓库、议题和 PR",
  "Files & folders": "文件和文件夹",
  "Posts & profile": "帖子和个人资料",
  "Lets the agent read and act in your Gmail, Calendar, and Sheets on your behalf, and read your Drive (it can save new files there, but not edit your existing ones).":
    "允许代理代你读取和操作 Gmail、Calendar 和 Sheets，并读取你的 Drive（它可以在其中保存新文件，但不能编辑你已有的文件）。",
  "Lets the agent act in Slack as you — read your channels and post messages on your behalf. (To chat with the agent in Slack, just DM it — you don't need this.)":
    "允许代理以你的身份在 Slack 中操作——读取你的频道并代你发消息。（要在 Slack 中与代理聊天，直接私信它即可——不需要这个。）",
  "Lets the agent read the Notion pages and databases you share with it (and edit them if you grant that access).":
    "允许代理读取你与它共享的 Notion 页面和数据库（如果你授予权限，也可以编辑它们）。",
  "Lets the agent read and update your Linear issues on your behalf.": "允许代理代你读取和更新 Linear 议题。",
  "Lets the agent read and update your GitHub repos, issues, and PRs on your behalf.":
    "允许代理代你读取和更新 GitHub 仓库、议题和 PR。",
  "Lets the agent browse, download, and upload files in your Dropbox on your behalf, and manage shared links.":
    "允许代理代你浏览、下载和上传 Dropbox 中的文件，并管理共享链接。",
  "Lets the agent read X and post, like, and follow as you — used when an action should come from your account rather than the org's.":
    "允许代理读取 X 并以你的身份发帖、点赞和关注——用于需要以你的账号而非组织账号执行的操作。",
  "Encrypted at rest": "静态加密存储",
  "Expires {date}": "{date} 到期",
  "Added {date}": "添加于 {date}",
  Expired: "已过期",
  "Last used {date} in {scope} · {status}": "上次使用：{date}，于 {scope} · {status}",
  "No audited use yet": "暂无经审计的使用记录",
  "Pending requests": "待处理的请求",
  "requested {mode} access": "请求{mode}访问权限",
  standing: "长期",
  once: "一次性",
  "expires {date}": "{date} 到期",
  "Active access": "当前授权",
  Revoke: "撤销",
  "{kind}: {name}": "{kind}：{name}",
  Personal: "个人",
  Channel: "频道",
  Group: "群组",
  Org: "组织",
  "New credential": "新凭据",
  "Add a credential": "添加凭据",
  "Describe the credential here, then paste the secret itself on a private one-time page. It goes straight to your encrypted keychain — it is never shown in chat or stored on this page.":
    "在此描述凭据，然后在私密的一次性页面上粘贴密钥本身。它会直接进入你的加密钥匙串——不会显示在对话中，也不会存储在本页面上。",
  "Your one-time page is ready": "你的一次性页面已就绪",
  "Open it in a new tab and paste the secret there.": "在新标签页中打开它，并在那里粘贴密钥。",
  "Open the one-time page": "打开一次性页面",
  Done: "完成",
  Service: "服务",
  "Environment variable": "环境变量",
  optional: "可选",
  Purpose: "用途",
  "What may the agent use this credential for?": "代理可以用这个凭据做什么？",
  "Preparing…": "正在准备…",
  "{name}: connected.": "{name}：已连接。",
  "{name}: connection failed.": "{name}：连接失败。",
  "Not connected": "未连接",
  "Reconnect needed": "需要重新连接",
  "Refresh failed: {error}": "刷新失败：{error}",
  Reconnect: "重新连接",
  "Connect account": "连接账号",
  Disconnect: "断开连接",
  "Accounts and credentials your agent may use on your behalf.": "代理可以代你使用的账号和凭据。",
  "Secrets stay encrypted and every use or shared grant is audited.":
    "密钥始终保持加密，每次使用或共享授权都会留有审计记录。",
  "Refresh keychain": "刷新钥匙串",
  "Add credential": "添加凭据",
  "Keychain summary": "钥匙串摘要",
  "Connected accounts": "已连接账号",
  "Stored credentials": "已存储凭据",
  "Active grants": "有效授权",
  "Need attention": "需要关注",
  "Loading your keychain…": "正在加载你的钥匙串…",
  "Linked accounts": "已关联账号",
  "Provider APIs the agent can use as you.": "代理可以以你的身份使用的服务商 API。",
  "No accounts available": "没有可用账号",
  "Your workspace has not configured any account providers yet.": "你的工作区尚未配置任何账号服务商。",
  "API keys, tokens, and files you added through the one-time page.": "你通过一次性页面添加的 API 密钥、令牌和文件。",
  "No stored credentials": "没有已存储的凭据",
  "Add one without pasting a secret into chat.": "无需在对话中粘贴密钥即可添加。",
  "Failed to load connectors.": "加载连接器失败。",
  "Failed to load stored keys.": "加载已存储的密钥失败。",
  "It will immediately revoke {count} active grant: {list}.": "它将立即撤销 {count} 个有效授权：{list}。",
  "It will immediately revoke {count} active grants: {list}.": "它将立即撤销 {count} 个有效授权：{list}。",
  "Automations using it may stop working. The credential cannot be recovered.":
    "使用它的自动化可能会停止工作。该凭据无法恢复。",
  "Delete {service}?": "删除 {service}？",
  "Delete credential": "删除凭据",
  "Another keychain change is still in progress.": "另一个钥匙串更改仍在进行中。",
  "Could not delete the key.": "无法删除该密钥。",
  "Revoke access for {scope}?": "撤销 {scope} 的访问权限？",
  "This {mode} access ends immediately. Automations using it may stop working.":
    "此{mode}访问权限将立即终止。使用它的自动化可能会停止工作。",
  "Revoke access": "撤销访问权限",
  "Access revoked ✓": "访问权限已撤销 ✓",
  "Could not revoke access.": "无法撤销访问权限。",
  "Service and purpose are required.": "服务和用途为必填项。",
  "No one-time page URL was returned.": "未返回一次性页面 URL。",
  "Your one-time page is ready.": "你的一次性页面已就绪。",
  "Could not create the one-time page.": "无法创建一次性页面。",
  "No authorization URL was returned.": "未返回授权 URL。",
  "Could not start the connector.": "无法启动连接器。",
  "It will also stop {count} active credential grant for this account.": "它还将停止此账号的 {count} 个有效凭据授权。",
  "It will also stop {count} active credential grants for this account.": "它还将停止此账号的 {count} 个有效凭据授权。",
  "Disconnect {name}?": "断开 {name} 的连接？",
  "Automations using this account may stop working.": "使用此账号的自动化可能会停止工作。",
  "Disconnect account": "断开账号连接",
  "Could not disconnect.": "无法断开连接。",

  "Failed to load contexts.": "加载上下文失败。",
  "{count} member": "{count} 名成员",
  "{count} members": "{count} 名成员",
  "Just you — your web chats and DMs with the agent live here.": "只有你——你与代理的网页聊天和私信都在这里。",
  "Group DM": "群组私信",
  "Shared with everyone in this group conversation.": "与此群组对话中的所有人共享。",
  "Shared with everyone in this channel.": "与此频道中的所有人共享。",
  "Shared personal space": "共享的个人空间",
  "In {title}": "在 {title} 中",
  "All contexts": "所有上下文",
  "Filter by: {label}": "筛选：{label}",
  "Filter by context": "按上下文筛选",
  "Loading projects…": "正在加载项目…",
  "No projects match your search.": "没有符合搜索的项目。",
  "No projects yet.": "还没有项目。",
  "Refresh projects": "刷新项目",
  "New project": "新建项目",
  "Search projects": "搜索项目",
  "Search projects…": "搜索项目…",
  Show: "显示",
  "Active only": "仅活跃",
  Everything: "全部",
  "1 conversation": "1 个对话",
  "{count} conversations": "{count} 个对话",
  shared: "共享",
  owned: "自有",
  private: "私有",
  "Private channel": "私有频道",
  "active {time}": "活跃于 {time}",
  "The agent's files and memory here are separate from your other contexts.":
    "代理在此的文件和记忆与你的其他上下文相互独立。",
  "Add people": "添加成员",
  "This project is ready for work": "此项目已就绪，可以开始工作",
  "Start a conversation with New chat. Files, automations, and other work created there will stay scoped to this project.":
    "通过「新对话」开始对话。在那里创建的文件、自动化和其他工作都将归属此项目。",
  Conversations: "对话",
  "No conversations yet.": "还没有对话。",
  "Project settings": "项目设置",
  "Context settings": "上下文设置",
  People: "成员",
  You: "你",
  "Remove {label}": "移除 {label}",
  "Everyone matching is already in this project.": "所有匹配的人都已在此项目中。",
  "No matches for “{query}”.": "没有匹配「{query}」的结果。",
  "Searching…": "正在搜索…",
  "Working…": "正在处理…",
  "Search by name or handle": "按姓名或用户名搜索",
  Search: "搜索",
  Close: "关闭",
  "Loading this context's files, crons, apps and skills…": "正在加载此上下文的文件、定时任务、应用和技能…",
  "View all": "查看全部",
  "Delete this cron? This can't be undone.": "删除此定时任务？此操作无法撤销。",
  "Couldn't update that cron.": "无法更新该定时任务。",
  "Delete this skill? This can't be undone.": "删除此技能？此操作无法撤销。",
  "Couldn't delete that skill.": "无法删除该技能。",
  manage: "可管理",
  read: "只读",
  "Close new project": "关闭新建项目对话框",
  "launch cohort": "上线冲刺",
  "Enter a project name.": "请输入项目名称。",
  "Creating…": "正在创建…",
  "Create project": "创建项目",
  "Core returned an invalid project": "核心服务返回了无效的项目数据",
  "Couldn't create that project.": "无法创建该项目。",
  "Enter at least two characters.": "请至少输入两个字符。",
  "Couldn't search for people.": "无法搜索成员。",
  "Couldn't add that person.": "无法添加该成员。",
  "Remove {label} from {project}?": "将 {label} 从 {project} 中移除？",
  "this project": "此项目",
  "Couldn't remove that person.": "无法移除该成员。",
  "Failed to load this context's resources.": "加载此上下文的资源失败。",
  "Read-only — replies happen on the original surface": "只读——请在原始平台上回复",

  "Couldn't load this project's model.": "无法加载此项目的模型。",
  "Saved — new conversations here run on {model}.": "已保存——此处的新对话将使用 {model}。",
  "Couldn't change the model — try again.": "无法更改模型——请重试。",
  Model: "模型",
  "The model every conversation here starts on.": "此处每个对话默认使用的模型。",
  "Default model for this project": "此项目的默认模型",
  "Org default ({model})": "组织默认（{model}）",
  "{model} — no longer offered": "{model}——不再提供",
  "Following the org default — it changes when the org's does.": "跟随组织默认——组织默认更改时随之更改。",
  "Pinned for this project. Anyone in a chat can still pick a different model for that conversation.":
    "已固定用于此项目。对话中的任何人仍可为该对话选择其他模型。",
  "The channel description in Slack names this model.": "Slack 频道简介中会注明此模型。",
};
