export const zhSessions: Record<string, string> = {
  "Web chat": "网页对话",
  Channel: "频道",
  "Group DM": "群组私聊",
  "Direct message": "私聊",
  Pinned: "置顶",
  Archived: "已归档",
  "Loading conversations...": "正在加载会话…",
  "Slack conversations hidden.": "Slack 会话已隐藏。",
  "No conversations yet.": "暂无会话。",
  Project: "项目",
  "{name} project": "{name}项目",
  "Project options": "项目选项",
  "Options for {name}": "{name}的选项",
  "New chat in {name}": "在{name}中新建对话",
  "View project": "查看项目",
  Rename: "重命名",
  "Rename project": "重命名项目",
  "No conversations yet — start a new chat.": "暂无会话——开始新对话吧。",
  "Loading conversations…": "正在加载会话…",
  "No conversations match.": "没有匹配的会话。",
  "Search chats…": "搜索对话…",
  "Conversation status": "会话状态",
  Active: "活跃",
  Waiting: "待回复",
  Surface: "来源",
  "All surfaces": "全部来源",
  Web: "网页",
  Personal: "个人",
  "Agent is working": "助手正在工作",
  "Waiting for your reply": "等待你的回复",
  "{label} — click to inspect": "{label} — 点击查看",
  "Read-only": "只读",
  "Copy link": "复制链接",
  "Copy link to {title}": "复制{title}的链接",
  Unpin: "取消置顶",
  Pin: "置顶",
  Unarchive: "取消归档",
  Archive: "归档",
  "agent is working": "助手正在工作",
  "waiting for your reply": "等待你的回复",
  "read-only": "只读",
  pinned: "已置顶",
  "Conversation options": "会话选项",
  "Refreshing title": "正在刷新标题",
  "Refresh title": "刷新标题",
  "Row color": "行颜色",
  "Color row {color}": "行颜色 {color}",
  "Custom color (RGB picker)": "自定义颜色（RGB 选择器）",
  "Custom row color": "自定义行颜色",
  "Clear color": "清除颜色",
  "Clear row color": "清除行颜色",
  "Rename conversation": "重命名会话",
  "Failed to load conversations.": "加载会话失败。",
  "Couldn't load this conversation. Check your connection and click it again.":
    "无法加载此会话。请检查网络连接后重新点击。",
  Today: "今天",
  Yesterday: "昨天",
  "Previous 7 days": "过去 7 天",
  "Previous 30 days": "过去 30 天",
  Older: "更早",
  "1 background job running": "1 个后台任务运行中",
  "{count} background jobs running": "{count} 个后台任务运行中",
  "1 watch armed": "1 个监视已启用",
  "{count} watches armed": "{count} 个监视已启用",
  "Pasted text · {count} chars": "已粘贴的文本 · {count} 字符",
  "Shared channel": "共享频道",
  Group: "群组",
  "No active run to signal.": "当前没有正在运行的任务。",
  "Could not send the approval.": "无法发送审批。",
  "The agent run failed.": "助手运行失败。",
  "Timed out waiting for the agent to respond.": "等待助手响应超时。",
  "Denied.": "已拒绝。",
  file: "文件",
  "{count} tiles is the limit — drop it on a tab strip instead": "最多 {count} 个分屏区域——请改为拖到标签栏上",
  Conversation: "会话",
  "Already open in a pane": "已在窗格中打开",
  "{count} conversations is all one canvas holds — close one first":
    "一个画布最多容纳 {count} 个会话——请先关闭一个",
  "{count} tiles is the limit — opened as a tab": "最多 {count} 个分屏区域——已作为标签页打开",
  "Start the chat first, then open it full screen": "请先开始对话，再全屏打开",
  "Still syncing this conversation — try again in a moment": "此会话仍在同步——请稍后再试",
  "Open here": "在此打开",
  "Split left": "向左拆分",
  "Split right": "向右拆分",
  "Split up": "向上拆分",
  "Split down": "向下拆分",
  "Close pane": "关闭窗格",
  "Split this pane with a new session": "用新会话拆分此窗格",
  "Restore to grid (Esc)": "恢复网格布局（Esc）",
  "Focus this pane over the grid": "聚焦此窗格",
  "Open full screen": "全屏打开",
};
