export const zhShell: Record<string, string> = {
  "Back to admin": "返回管理后台",
  "Language: 中文 / English": "语言：中文 / English",
  "Color scheme: light / dark / system": "配色：浅色 / 深色 / 跟随系统",
  "Sign out": "退出登录",
  "Viewing the assistant as {user} — you are {by}": "正在以 {user} 的身份查看助手 — 你是 {by}",
  "Exit impersonation": "退出模拟身份",
  "Dev mode — no identity provider, signed in as {user}": "开发模式 — 无身份提供方，已登录为 {user}",
  "Sign in through the portal": "通过门户登录",
  "This surface is reached through the portal, and signing in there didn't produce a session for it. Open the portal address directly rather than this one.":
    "此界面需经门户访问，而在门户登录并未为它建立会话。请直接打开门户地址，而不是本地址。",
  "If you opened this surface's own address, that's the cause — it can't authenticate anyone on its own.":
    "如果你打开的是本界面自己的地址，这就是原因——它无法独立完成身份验证。",
  "Switch to English": "切换到英文",
  "Switch to 中文": "切换到中文",
  "Your session ended": "会话已结束",
  "You've been signed out. Sign in again and you'll come back to this page.":
    "你已退出登录。重新登录后会回到本页面。",
  "Sign in": "登录",
  "You don't have access": "你没有访问权限",
  "Your account is signed in and verified — it just isn't allowed on this instance. Ask an administrator to add you.":
    "你的账号已登录并通过验证，但未获准使用此实例。请联系管理员添加你。",
  "We couldn't reach the assistant": "无法连接助手服务",
  "The service didn't respond. This is usually temporary.": "服务没有响应，通常是暂时性的。",
  "Try again": "重试",
  "If this keeps happening, the core service may be down.": "如果持续出现，核心服务可能已宕机。",
  "Dev sign-in": "开发登录",
  "No identity provider is configured, so this instance trusts a local cookie. Set":
    "未配置身份提供方，此实例信任本地 cookie。设置",
  "and run the portal to use real sign-in.": "并运行门户以使用真实登录。",
  Principal: "账号",
  "Signing in…": "正在登录…",
  Continue: "继续",
  "Sign-in failed.": "登录失败。",
  "Hide sidebar": "收起侧栏",
  "Show sidebar": "展开侧栏",
  "Close sidebar": "关闭侧栏",
  "Resize sidebar": "调整侧栏宽度",
  "Drag to resize · double-click to reset": "拖动调整宽度 · 双击重置",
  "Pick a conversation, or start a new chat.": "选择一个会话，或开始新对话。",
  "Hide {title}": "收起{title}",
  "Show {title}": "展开{title}",
  "New session": "新会话",
  "New chat": "新对话",
  Browse: "浏览",
  Projects: "项目",
  Chats: "对话",
  Files: "文件",
  Crons: "定时任务",
  Keychain: "钥匙串",
  Apps: "应用",
  Memory: "记忆",
  Skills: "技能",
  Sessions: "会话",
  "Showing web chats only": "仅显示网页对话",
  "Hide non-web conversations": "隐藏非网页会话",
  "Web only": "仅网页",
  "Refresh {title}": "刷新{title}",
  "This edit link is missing a valid app name.": "此编辑链接缺少有效的应用名称。",
  "That conversation wasn't found, or you don't have access to it.": "未找到该会话，或你没有访问权限。",
};
