export const zhSkills: Record<string, string> = {
  "1 asset": "1 个资产",
  "1 group": "1 个分组",
  "1 skill": "1 个技能",
  "Act immediately": "立即处理",
  "Active": "活跃",
  "Add bot": "添加机器人",
  "Agent behavior": "代理行为",
  "All": "全部",
  "All scopes": "全部作用域",
  "All sources": "全部来源",
  "Ambient behavior": "环境感知行为",
  "Archive": "归档",
  "Archive /{name}?": "归档 /{name}？",
  "Archive skill": "归档技能",
  "Archived": "已归档",
  "Archiving…": "正在归档…",
  "Automated posters": "自动发帖者",
  "Available to": "可用于",
  "Available to {target}": "对 {target} 可用",
  "Back to skills": "返回技能列表",
  "Batch interval for {name} in hours": "{name} 的批量汇总间隔（小时）",
  "Batch updates": "批量汇总",
  "Bot name": "机器人名称",
  "Cancel": "取消",
  "Capabilities": "能力",
  "changed": "已更改",
  "Channel": "频道",
  "Choose what this project should notice and act on.": "选择此项目应关注并处理的内容。",
  "Clear filters": "清除筛选",
  "Control how messages from bots and integrations wake the agent.": "控制来自机器人和集成的消息如何唤醒代理。",
  "Couldn't load this scope's standing orders.": "无法加载此作用域的常驻指令。",
  "Couldn't save — try again.": "保存失败 —— 请重试。",
  "Create a reusable procedure for yourself or a shared context.": "为自己或共享上下文创建一个可复用的流程。",
  "Create skill": "创建技能",
  "Created here": "在此处创建",
  "Default (on when standing orders are set)": "默认（设置常驻指令时开启）",
  "Default: on only when standing orders (or an action-mode bot) are set below — otherwise mention-only.":
    "默认：仅在下方设置了常驻指令（或立即处理模式的机器人）时开启 —— 否则仅响应提及。",
  "Description": "描述",
  "Description {status}": "描述{status}",
  "Details": "详情",
  "Edit": "编辑",
  "Edit /{name}": "编辑 /{name}",
  "Editing": "编辑中",
  "every": "每",
  "Everyone in a shared context can invoke and edit this skill.": "共享上下文中的每个人都可以调用和编辑此技能。",
  "Everyone in this context can invoke and edit these instructions.":
    "此上下文中的每个人都可以调用和编辑这些说明。",
  "Everyone in this context can invoke the updated instructions.":
    "此上下文中的每个人都可以调用更新后的说明。",
  "everyone in {scope}": "{scope} 中的每个人",
  "Failed to archive skill.": "归档技能失败。",
  "Failed to create skill.": "创建技能失败。",
  "Failed to load skill details.": "加载技能详情失败。",
  "Failed to load skills.": "加载技能失败。",
  "Failed to restore skill.": "恢复技能失败。",
  "Failed to save skill.": "保存技能失败。",
  "Filter by skill status": "按技能状态筛选",
  "Filter skills by scope": "按作用域筛选技能",
  "Filter skills by source": "按来源筛选技能",
  "For example: Flag anything that could delay the launch.": "例如：标记任何可能延误发布的事项。",
  "Group": "群组",
  "h": "小时",
  "Handling for {name}": "{name} 的处理方式",
  "If it overrides a broader /{name}, that version becomes effective.":
    "如果它覆盖了更广作用域的 /{name}，那个版本将生效。",
  "Ignore": "忽略",
  "Instructions": "说明",
  "Instructions unavailable.": "说明不可用。",
  "instructions {status}": "说明{status}",
  "Its history and assets are kept, and you can restore it later.": "其历史和资产都会保留，你可以稍后恢复。",
  "Loading instructions…": "正在加载说明…",
  "Loading skill instructions…": "正在加载技能说明…",
  "Loading skills…": "正在加载技能…",
  "Loading…": "正在加载…",
  "Name": "名称",
  "Name, description, and instructions are all required.": "名称、描述和说明均为必填。",
  "Narrower scope takes precedence where both apply": "两者都适用时，更窄的作用域优先",
  "New": "新建",
  "New skill": "新建技能",
  "No bots added. All bot posts are treated as activity.": "未添加机器人。所有机器人消息都会被视为活动。",
  "No skills available yet.": "暂无可用技能。",
  "No skills match these filters.": "没有符合这些筛选条件的技能。",
  "None required": "无要求",
  "Off": "关闭",
  "On": "开启",
  "One line: what it does / when to use it": "一句话：它做什么 / 何时使用",
  "only you": "仅你",
  "Organization": "组织",
  "Overrides": "覆盖",
  "Pack {name}": "技能包 {name}",
  "Personal": "个人",
  "Personal — only you": "个人 —— 仅你",
  "Plain-language guidance for proactive work. Leave empty to respond only when addressed.":
    "用自然语言描述主动工作的指引。留空则仅在被提及时响应。",
  "Project / group": "项目 / 群组",
  "Publish /{name} to {scope}?": "将 /{name} 发布到 {scope}？",
  "Publish change": "发布更改",
  "Publish skill": "发布技能",
  "Publish this change to {scope}?": "将此更改发布到 {scope}？",
  "Remove": "移除",
  "Remove {name} from the ledger": "将 {name} 从名单中移除",
  "Restore": "恢复",
  "Review again": "重新检查",
  "Save": "保存",
  "Saved.": "已保存。",
  "Saving…": "正在保存…",
  "Scope": "作用域",
  "Scope variant": "作用域变体",
  "Search skills…": "搜索技能…",
  "Skill packs": "技能包",
  "Skills": "技能",
  "Source": "来源",
  "Standing orders": "常驻指令",
  "Team": "团队",
  "The SKILL.md contents — the steps to follow when this skill is used.":
    "SKILL.md 的内容 —— 使用此技能时要遵循的步骤。",
  "This version will stop being available to {audience}.": "此版本将不再对{audience}可用。",
  "this context": "此上下文",
  "this {scope}": "此{scope}",
  "Treat like a person": "像真人一样对待",
  "unchanged": "未更改",
  "When off, the agent never acts on overheard messages here — it only responds to direct @mentions.":
    "关闭时，代理不会响应此处旁听到的消息 —— 只回应直接 @提及。",
  "Working…": "处理中…",
  "you": "你",
  "{count} assets": "{count} 个资产",
  "{count} groups": "{count} 个分组",
  "{count} skills": "{count} 个技能",
  "{count} variants": "{count} 个变体",
  "{skills} in {groups}": "{skills}，分属 {groups}",
  "“{name}” is already in the ledger.": "“{name}” 已在名单中。",
};
